# Generated by Django 2.2.4 on 2019-09-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_auto_20190909_1135'),
        ('registro', '0002_auto_20190826_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mybooks',
            field=models.ManyToManyField(to='livros.Book'),
        ),
    ]
