# Generated by Django 2.2.4 on 2019-08-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('autor', models.CharField(max_length=30)),
                ('editora', models.CharField(max_length=30)),
            ],
        ),
    ]
