# Generated by Django 2.2.4 on 2019-09-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='titulo',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
