version: '3'

services:
  db:
    image: mysql:5.7.27
    ports:
      - "3306:3306"
    environment:
     MYSQL_DATABASE: 'bd-livros'
     MYSQL_USER: 'root'
     MYSQL_PASSWORD: 'password'
     MYSQL_ROOT_PASSWORD: 'password'
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src:/bdlivros
    ports:
      - "8000:8000"
    depends_on:
      - db
